<a href="https://colab.research.google.com/github/lapinRagnar/my-deep-learning-pytorch/blob/main/00_introduction_to_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intoduction to tensors

# **site du tuto**


---


https://www.youtube.com/watch?v=Z_ikDlimN6A

https://www.learnpytorch.io/

https://github.com/mrdbourke/pytorch-deep-learning

exercices :
https://github.com/mrdbourke/pytorch-deep-learning/tree/main/extras


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


# **creating tensors** 

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
MATRIX = torch.tensor([[2, 5], 
                       [8, 9]])

In [ ]:
MATRIX

tensor([[2, 5],
        [8, 9]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]
                        ]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

# **Random tensors**

`start with random number -> look at data -> update random number -> look at data -> update random numbers`

In [ ]:
# create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4308, 0.3318, 0.0837, 0.4383],
        [0.7317, 0.2368, 0.2730, 0.7499],
        [0.0319, 0.3701, 0.7247, 0.5363]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height,width, color channel (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zero and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

# Create a range of tensors and tensors-like

In [ ]:
# use torch.range()
one_to_ten = torch.arange(1, 11)
one_to_ten



tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_hundred_step_20 = torch.arange(start=1, end=100, step=20)
one_to_hundred_step_20

tensor([ 1, 21, 41, 61, 81])

In [ ]:
# creation tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# tensor datatype

In [ ]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0])
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([2., 5., 4.], dtype=torch.float16)
float_16_tensor

tensor([2., 5., 4.], dtype=torch.float16)

# getting information from tensions (tensors attributes)

1. tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. tensor not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1208, 0.8276, 0.5123, 0.6493],
        [0.0680, 0.9582, 0.6763, 0.0064],
        [0.3438, 0.8465, 0.3302, 0.1184]])

In [ ]:
# find out the details about some tensor
print(some_tensor)
print(f"datatype of tensor = {some_tensor.dtype} ") 
print(f"device tensor is on = {some_tensor.device} ") 
print(f"shape of tensor = {some_tensor.shape} ") 

tensor([[0.1208, 0.8276, 0.5123, 0.6493],
        [0.0680, 0.9582, 0.6763, 0.0064],
        [0.3438, 0.8465, 0.3302, 0.1184]])
datatype of tensor = torch.float32 
device tensor is on = cpu 
shape of tensor = torch.Size([3, 4]) 


# Maniputating tensors (tensors operations)
tensor operations include :
* addition
* substraction
* multiplication
* division
* matrix multiplication

In [ ]:
# create a tensor and add 10 to it
tensor = torch.tensor([1, 5, 8])
tensor + 10

tensor([11, 15, 18])

In [ ]:
# mupltiply tensor by ten
tensor = tensor * 10
tensor

tensor([10, 50, 80])

In [ ]:
# substract by 10
tensor - 10

tensor([ 0, 40, 70])

In [ ]:
# try out pytorch in-build functions
torch.mul(tensor, 10)

tensor([100, 500, 800])

In [ ]:
tensor.add(tensor + 55)

tensor([ 75, 155, 215])

# matrix multiplication
two main ways of performing multiplication in neural network and deep learning

1. element-wise multiplication
2. matrix multiplication

# there are two main rules that performing matrix multiplication needs to satisfy
1. the **inner dimensions** must match :
* `(3, 2) @ (3, 2) ` won't work
* ` (2, 3) @ (3, 2) ` will work
* ` (3, 2) @ (2, 3) ` will work

2. the resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` --> `(2, 2)`
* ` (3, 2) @ (2, 3) ` --> `(3, 3)`


In [ ]:
# element-wise multipication
print(tensor, "*", tensor)
print(f"equals: {tensor * tensor} ")

tensor([10, 50, 80]) * tensor([10, 50, 80])
equals: tensor([ 100, 2500, 6400]) 


In [ ]:
# matrix multiplication 
torch.matmul(tensor, tensor)

tensor(9000)

In [ ]:
x = torch.rand(3, 2)
print(x)

y = torch.rand(2, 3)
print(y)

print(torch.matmul(x, y))

tensor([[0.7548, 0.7523],
        [0.4385, 0.0806],
        [0.4392, 0.0997]])
tensor([[0.2378, 0.1893, 0.2289],
        [0.2573, 0.2920, 0.0353]])
tensor([[0.3731, 0.3626, 0.1993],
        [0.1250, 0.1065, 0.1032],
        [0.1301, 0.1123, 0.1041]])


In [ ]:
# la transposition
print(x)
print(f"\n")
print(f"la transposition de x = {x.T} ")

tensor([[0.7548, 0.7523],
        [0.4385, 0.0806],
        [0.4392, 0.0997]])


la transposition de x = tensor([[0.7548, 0.4385, 0.4392],
        [0.7523, 0.0806, 0.0997]]) 


# Find the min, max, mean, sum, etc... (tensor agregation)

In [ ]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

# finding the positional min and max

In [ ]:
# find the position in tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [ ]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensor 

* reshaping - reshapes an input tensor to a defined shape
* view - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - removes all `1` dimension from a tensor
* - unsqueeze - add `1` dimension to a target tensor
* - permute - return a view of the inout with dimensions permuted (swapped) in a certain way


In [ ]:
# let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensor on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"previous tensor: {x_reshaped} ")
print(f"previous shape: {x_reshaped.shape} ")

# remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed} ")
print(f"new shape {x_squeezed.shape} ")

previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
previous shape: torch.Size([1, 9]) 

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
new shape torch.Size([9]) 


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"previous target: {x_squeezed} ")
print(f"previous shape: {x_squeezed.shape} ")

# add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed} ")
print(f"New shape: {x_unsqueezed.shape} ")


previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
previous shape: torch.Size([9]) 

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
New shape: torch.Size([1, 9]) 


In [ ]:
# torch.permute()
x_original = torch.rand(size=(224, 224, 3)) # [height, width, coulour_channels]
print(f"x_original: {x_original.shape} ")

# permute the original tensor to arrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->3
print(f"x_permuted: {x_permuted.shape} ")

x_original: torch.Size([224, 224, 3]) 
x_permuted: torch.Size([3, 224, 224]) 


## **Indexing (selecting data from tensor)**

indexing with pytorch is similar to indexing with numpy

In [ ]:
#  create a tensor
import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# ou
x[0, 0]

tensor([1, 2, 3])

In [ ]:
# ou
x[0][0]

tensor([1, 2, 3])

In [ ]:
# let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
# la valeur au milieu - la valeur 5
x[0][1][1]

tensor(5)

In [ ]:
# you can also use ":" to select "all" of the target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# get all values of the 0 dimension but only the 1 index of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# index on x to return 9
print(x)
print(x[0][2][2])

# index on x to return 3, 6, 9
print(x[:, :, 2])


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor(9)
tensor([[3, 6, 9]])


# **pytorch tensor & numpy**

numpy is a popular scientific python numerical computing library

and because of this, pytorch has functionality to interact with it

* data in numpy, want in pytorch tensor --> `torch.from_numpy(ndarray)`
* pytorch tensor --> numpy --> `torch.tensor.numpy()`



In [ ]:
# numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# change the value of array,what will this change to do `tensor`?
array = array + 1
array, tensor

# tensor is not changed

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype # same dtype than the original

dtype('float32')

In [ ]:
tensor.dtype

torch.float32

In [ ]:
# change the tensor, what happens to `numpy_tensor`
tensor = tensor + 1
tensor, numpy_tensor
# the original data is not changed

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproductibility (trying to take random out of random)
In short how a neural network learns:

`start with random numbers -> tensor operation -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and pytorch comes with the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

extra resource for reproducibility : 
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed


In [ ]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.1830, 0.2704, 0.0282, 0.6298],
        [0.5416, 0.4554, 0.2900, 0.0418],
        [0.3015, 0.1883, 0.8648, 0.7038]])
tensor([[0.6640, 0.7643, 0.5931, 0.7776],
        [0.8405, 0.2092, 0.5863, 0.5260],
        [0.1362, 0.7023, 0.6907, 0.6832]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


# Running tensors and pytorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + Nvidia hardware + pytorch behind the scenes to make everything hunky dory (good). 

 A. getting a GPUs : 

 1. easiest - use google colab for a free GPU.
 2. use your own GPU
 3. use cloud computing - GCP, AWS, Azure... These services allow you rent computer on the cloud and access them.

For pytorch since it's capable of running compute on GPU or CPU, it's best practice to setup device agnostic code :
https://pytorch.org/docs/stable/notes/cuda.html



In [ ]:
!nvidia-smi

Fri May  5 18:19:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   59C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Check for GPU access with pytorch

In [ ]:
# check for GPU access with pytorch
import torch

torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count the number of device
torch.cuda.device_count()

1

# Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU because using a GPU results is faster computations. 

In [ ]:
# create a tensor (default in CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

# Moving tensors back to CPU


In [ ]:
# if tensor is in GPU, can't transform it to numpy
# tensor_on_gpu.numpy()  # does not work! 

In [ ]:
# to fix the GPU tensor with numpy issue, we can first set it to the CPU 
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu 

array([1, 2, 3])

In [ ]:
tensor_on_gpu # stay unchanged

tensor([1, 2, 3], device='cuda:0')

# Exercices && extra-curriculum
* https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises
